// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20220206135317_InitialV4")]
    partial class InitialV4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Campaign", b =>
                {
                    b.Property<int>("CampaignID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PercentOfPrice")
                        .HasColumnType("float");

                    b.HasKey("CampaignID");

                    b.ToTable("Campaigns");

                    b.HasData(
                        new
                        {
                            CampaignID = 1,
                            Name = "BBQ Weekend",
                            PercentOfPrice = 20.0
                        },
                        new
                        {
                            CampaignID = 2,
                            Name = "Breakfast Sale",
                            PercentOfPrice = 15.0
                        },
                        new
                        {
                            CampaignID = 3,
                            Name = "Healthy Week",
                            PercentOfPrice = 25.0
                        });
                });

            modelBuilder.Entity("DAL.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.HasKey("DepartmentID");

                    b.HasIndex("StaffID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            Name = "Dairy",
                            StaffID = 3
                        },
                        new
                        {
                            DepartmentID = 2,
                            Name = "Bread",
                            StaffID = 2
                        },
                        new
                        {
                            DepartmentID = 3,
                            Name = "Meat",
                            StaffID = 2
                        },
                        new
                        {
                            DepartmentID = 4,
                            Name = "Drink",
                            StaffID = 1
                        },
                        new
                        {
                            DepartmentID = 5,
                            Name = "Fruit",
                            StaffID = 4
                        },
                        new
                        {
                            DepartmentID = 6,
                            Name = "Pantry",
                            StaffID = 1
                        });
                });

            modelBuilder.Entity("DAL.Models.ProductsInDepartment", b =>
                {
                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.HasKey("ProductID", "DepartmentID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("productsInDepartments");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            DepartmentID = 1
                        },
                        new
                        {
                            ProductID = 2,
                            DepartmentID = 1
                        },
                        new
                        {
                            ProductID = 3,
                            DepartmentID = 1
                        },
                        new
                        {
                            ProductID = 4,
                            DepartmentID = 2
                        },
                        new
                        {
                            ProductID = 5,
                            DepartmentID = 2
                        },
                        new
                        {
                            ProductID = 6,
                            DepartmentID = 2
                        },
                        new
                        {
                            ProductID = 7,
                            DepartmentID = 3
                        },
                        new
                        {
                            ProductID = 8,
                            DepartmentID = 3
                        },
                        new
                        {
                            ProductID = 9,
                            DepartmentID = 3
                        },
                        new
                        {
                            ProductID = 10,
                            DepartmentID = 4
                        },
                        new
                        {
                            ProductID = 11,
                            DepartmentID = 4
                        },
                        new
                        {
                            ProductID = 12,
                            DepartmentID = 4
                        },
                        new
                        {
                            ProductID = 13,
                            DepartmentID = 5
                        },
                        new
                        {
                            ProductID = 14,
                            DepartmentID = 5
                        },
                        new
                        {
                            ProductID = 15,
                            DepartmentID = 5
                        },
                        new
                        {
                            ProductID = 16,
                            DepartmentID = 6
                        },
                        new
                        {
                            ProductID = 17,
                            DepartmentID = 6
                        },
                        new
                        {
                            ProductID = 18,
                            DepartmentID = 6
                        });
                });

            modelBuilder.Entity("DAL.Models.StaffEmail", b =>
                {
                    b.Property<int>("EmailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.HasKey("EmailID");

                    b.HasIndex("StaffID");

                    b.ToTable("StaffEmails");

                    b.HasData(
                        new
                        {
                            EmailID = 1,
                            Email = "MrA@hotmail.com",
                            StaffID = 1
                        },
                        new
                        {
                            EmailID = 2,
                            Email = "JohnTheBoss@hotmail.com",
                            StaffID = 1
                        },
                        new
                        {
                            EmailID = 3,
                            Email = "bobbyb@gmail.com",
                            StaffID = 2
                        },
                        new
                        {
                            EmailID = 4,
                            Email = "Anna2001@gmail.com",
                            StaffID = 3
                        },
                        new
                        {
                            EmailID = 5,
                            Email = "Carlster98@outlook.com",
                            StaffID = 4
                        },
                        new
                        {
                            EmailID = 6,
                            Email = "Carl_N@outlook.com",
                            StaffID = 4
                        },
                        new
                        {
                            EmailID = 7,
                            Email = "Sarah.W@live.com",
                            StaffID = 5
                        });
                });

            modelBuilder.Entity("DAL.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CampaignID")
                        .HasColumnType("int");

                    b.Property<string>("Contents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("Date");

                    b.Property<DateTime>("InventoryDate")
                        .HasColumnType("Date");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("CampaignID");

                    b.HasIndex("StaffID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CampaignID = 2,
                            Contents = "Cow Milk",
                            ExpireDate = new DateTime(2022, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryDate = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Milk",
                            Price = 12.0,
                            StaffID = 3,
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 2,
                            CampaignID = 2,
                            Contents = "Churned Cream, Salt",
                            ExpireDate = new DateTime(2022, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryDate = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Butter",
                            Price = 9.0,
                            StaffID = 3,
                            Stock = 13
                        },
                        new
                        {
                            ProductID = 3,
                            CampaignID = 2,
                            Contents = "Fremented Milk",
                            ExpireDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryDate = new DateTime(2021, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Yogurt",
                            Price = 14.0,
                            StaffID = 3,
                            Stock = 2
                        },
                        new
                        {
                            ProductID = 4,
                            CampaignID = 2,
                            Contents = "Flour, Water",
                            ExpireDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryDate = new DateTime(2021, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "White Bread",
                            Price = 15.0,
                            StaffID = 1,
                            Stock = 22
                        },
                        new
                        {
                            ProductID = 5,
                            CampaignID = 3,
                            Contents = "Flour, Water, Oats",
                            ExpireDate = new DateTime(2022, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryDate = new DateTime(2021, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Whole Grain Bread",
                            Price = 18.0,
                            StaffID = 3,
                            Stock = 9
                        },
                        new
                        {
                            ProductID = 6,
                            Contents = "Flour, Water, Yeast",
                            ExpireDate = new DateTime(2022, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryDate = new DateTime(2021, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Baguette",
                            Price = 20.0,
                            StaffID = 3,
                            Stock = 15
                        },
                        new
                        {
                            ProductID = 7,
                            CampaignID = 1,
                            Contents = "Chicken",
                            ExpireDate = new DateTime(2022, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryDate = new DateTime(2021, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chicken",
                            Price = 35.0,
                            StaffID = 2,
                            Stock = 26
                        },
                        new
                        {
                            ProductID = 8,
                            CampaignID = 1,
                            Contents = "Cow Meat, Fat",
                            ExpireDate = new DateTime(2022, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryDate = new DateTime(2021, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Steak",
                            Price = 25.0,
                            StaffID = 2,
                            Stock = 11
                        },
                        new
                        {
                            ProductID = 9,
                            Contents = "Fish",
                            ExpireDate = new DateTime(2022, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryDate = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fish",
                            Price = 30.0,
                            StaffID = 2,
                            Stock = 2
                        },
                        new
                        {
                            ProductID = 10,
                            CampaignID = 3,
                            Contents = "Water",
                            ExpireDate = new DateTime(2022, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryDate = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Water",
                            Price = 5.0,
                            StaffID = 1,
                            Stock = 4
                        },
                        new
                        {
                            ProductID = 11,
                            Contents = "Carbonated Water, Flavor",
                            ExpireDate = new DateTime(2022, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryDate = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Soda",
                            Price = 15.0,
                            StaffID = 1,
                            Stock = 35
                        },
                        new
                        {
                            ProductID = 12,
                            CampaignID = 1,
                            Contents = "Fermented Wheat",
                            ExpireDate = new DateTime(2022, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryDate = new DateTime(2021, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Beer",
                            Price = 24.0,
                            StaffID = 5,
                            Stock = 15
                        },
                        new
                        {
                            ProductID = 13,
                            CampaignID = 3,
                            Contents = "",
                            ExpireDate = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryDate = new DateTime(2021, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Apple",
                            Price = 5.0,
                            StaffID = 4,
                            Stock = 14
                        },
                        new
                        {
                            ProductID = 14,
                            CampaignID = 3,
                            Contents = "",
                            ExpireDate = new DateTime(2022, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryDate = new DateTime(2021, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Orange",
                            Price = 8.0,
                            StaffID = 4,
                            Stock = 25
                        },
                        new
                        {
                            ProductID = 15,
                            CampaignID = 3,
                            Contents = "",
                            ExpireDate = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryDate = new DateTime(2021, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Melon",
                            Price = 15.0,
                            StaffID = 3,
                            Stock = 1
                        },
                        new
                        {
                            ProductID = 16,
                            Contents = "Wheat",
                            ExpireDate = new DateTime(2022, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryDate = new DateTime(2021, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Flour",
                            Price = 10.0,
                            StaffID = 1,
                            Stock = 17
                        },
                        new
                        {
                            ProductID = 17,
                            Contents = "Tomatoes",
                            ExpireDate = new DateTime(2022, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryDate = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Canned Tomatoes",
                            Price = 5.0,
                            StaffID = 5,
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 18,
                            Contents = "",
                            ExpireDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryDate = new DateTime(2021, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cooking Oil",
                            Price = 24.0,
                            StaffID = 5,
                            Stock = 21
                        });
                });

            modelBuilder.Entity("DAL.Staff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("Date");

                    b.Property<int?>("MentorID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffID");

                    b.HasIndex("MentorID");

                    b.HasIndex("PersonalNumber")
                        .IsUnique()
                        .HasFilter("[PersonalNumber] IS NOT NULL");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            StaffID = 1,
                            Name = "John A",
                            PersonalNumber = "19680413-5436",
                            PhoneNumber = "070-5002138"
                        },
                        new
                        {
                            StaffID = 2,
                            Name = "Bob B",
                            PersonalNumber = "19531030-8564",
                            PhoneNumber = "078-3219543"
                        },
                        new
                        {
                            StaffID = 3,
                            EndDate = new DateTime(2022, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MentorID = 1,
                            Name = "Anna H",
                            PersonalNumber = "20010121-9451",
                            PhoneNumber = "076-8659302"
                        },
                        new
                        {
                            StaffID = 4,
                            EndDate = new DateTime(2022, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MentorID = 2,
                            Name = "Carl N",
                            PersonalNumber = "19980715-7203",
                            PhoneNumber = "076-3246012"
                        },
                        new
                        {
                            StaffID = 5,
                            EndDate = new DateTime(2022, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MentorID = 2,
                            Name = "Sarah W",
                            PersonalNumber = "19921003-3241",
                            PhoneNumber = "075-5346295"
                        });
                });

            modelBuilder.Entity("DAL.Department", b =>
                {
                    b.HasOne("DAL.Staff", "Staff")
                        .WithMany("Departments")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DAL.Models.ProductsInDepartment", b =>
                {
                    b.HasOne("DAL.Department", "Department")
                        .WithMany("ProductDepartment")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Product", "Product")
                        .WithMany("ProductDepartment")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DAL.Models.StaffEmail", b =>
                {
                    b.HasOne("DAL.Staff", "Staff")
                        .WithMany("Emails")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DAL.Product", b =>
                {
                    b.HasOne("DAL.Campaign", "Campaign")
                        .WithMany("Products")
                        .HasForeignKey("CampaignID");

                    b.HasOne("DAL.Staff", "Staff")
                        .WithMany("Products")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DAL.Staff", b =>
                {
                    b.HasOne("DAL.Staff", "Mentor")
                        .WithMany("Staffs")
                        .HasForeignKey("MentorID");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("DAL.Campaign", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DAL.Department", b =>
                {
                    b.Navigation("ProductDepartment");
                });

            modelBuilder.Entity("DAL.Product", b =>
                {
                    b.Navigation("ProductDepartment");
                });

            modelBuilder.Entity("DAL.Staff", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Emails");

                    b.Navigation("Products");

                    b.Navigation("Staffs");
                });
#pragma warning restore 612, 618
        }
    }
}
